apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

configMapGenerator:
  - name: grafana-provisioning
    files:
      - provisioning/datasources/datasources.yaml
      - provisioning/dashboards/dashboard-provider.yaml
  - name: grafana-dashboards
    files:
      - dashboards/executive-slo.json
      - dashboards/customer-journey.json
      - dashboards/platform-golden-signals.json

generatorOptions:
  disableNameSuffixHash: true
