name: CI Prod

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-cicd.yml
    with:
      environment_name: prod
      namespace: marketplace-prod
      overlay: prod
      deploy: false
      build_images: true
      push_images: true
      sign_images: true
      run_tests: true
      run_frontend: true
      validate_k8s: true
      validate_k8s_all: false
      policy_check: true
      canary_checks: false
      create_namespace: false
    secrets: inherit
