name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/reusable-cicd.yml
    with:
      environment_name: dev
      namespace: marketplace-dev
      overlay: dev
      deploy: false
      build_images: false
      push_images: false
      sign_images: false
      run_tests: true
      run_frontend: true
      validate_k8s: false
      validate_k8s_all: true
      policy_check: true
      canary_checks: false
      create_namespace: false
    secrets: inherit
